server.port: 7001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false
    username: root
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  devtools:
    restart:
      enabled: false

